/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hILHyfZl9TX
 */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function Landing() {
  return (
    <section className="w-[100vw] flex justify-center">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center text-center">
          <div className="space-y-2 mt-40">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
              Welcome to Our Company
            </h1>
            <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Enter your query below to start searching
            </p>
          </div>
          <div className="flex flex-col mt-14 md:flex-row w-full max-w-md items-center space-x-2">
            <Input
              className="focus:(mt-0)"
              placeholder="Search here..."
              type="search"
            />
            <Button className="mt-4 md:mt-0" type="submit">
              Search
            </Button>
          </div>
        </div>
      </div>
    </section>
  );
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
