[workspace]
members = ["methods", "relay"]
resolver = "2"

[workspace.dependencies]
risc0-build = { version = "0.20.1" }
risc0-zkvm = { version = "0.20.1", default-features = false }
bonsai-sdk = { version = "0.5.1" }
bonsai-ethereum-relay = { version = "0.5.1" }
methods = { path = "./methods", package = "bonsai-starter-methods" }

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
